### ISSUE TITLE
Create 404 component

### ISSUE THREAD

**Issue by iPzard** [default-services/components#3]
Create a `FileNotFound.js` 404-page component which is designed to use as a [custom 404 web page](https://en.wikipedia.org/wiki/HTTP_404#Custom_error_pages).

**Comment by dragon3h** [comment]
i'll take it
have some questions:
1. do we have mock fot it
2. what is gitflow:  branch naming convention - e.g.  new branch:   feature-404page

**Comment by iPzard** [comment]
Thanks, much appreciated!

1. do we have mock for it?
My thoughts are something basic and generic that would work for any project (we can always add variant options later too). Here's an basic example..
https://codepen.io/iPzard/pen/852c4d134aded18a6ad123b3702186d9

2. what is gitflow: branch naming convention - e.g. new branch: feature-404page?
Good catch.. Yes, as you mentioned would be best. I'll be sure to update the contribution Wiki shortly here today w/that too.

**Comment by dragon3h** [comment]
1. .idea id related to Webstorm config
2. fixed review issues
